<div class="media">
    <p class="pull-left">
        <a href="<?=url("/app?id={$app->getId()}")?>">
            <img class="app-icon media-object img-rounded" src="<?=$app->getIconUrl()?>">
        </a>
    </p>
    <div class="media-body">
        <h2 class="media-hedding"><a href="<?=url("/app?id={$app->getId()}")?>"><?=htmlspecialchars($app->getTitle())?></a></h2>
    </div>
</div>

<div class="row">
    <div class="col-sm-4 col-md-3 hidden-xs">
        <?=block('pkg_infopanel')?>
    </div>

    <div class="col-xs-12 col-sm-8 col-md-9">

        <h3>
            <a href="<?=url("/package?id={$package->getId()}")?>">
                <?=block('platform_icon')?>
                <?=htmlspecialchars($package->getTitle())?>
            </a>
<?php if($package->isProtected()): ?>
            <i class="fa fa-lock"></i>
<?php endif ?>
        </h3>

        <h4>GuestPass URL</h4>
        <p><a href="<?=$guestpass_url?>"><?=$guestpass_url?></a></p>
        <dl class="dl-horizontal">
            <dt>Expired at</dt>
            <dd><?=$expire?></dd>
            <dt>Generated by</dt>
            <dd><?=$login_user->getMail()?></dd>
        </dl>
        <p class="text-center">
            <img src="<?=url("/qr/code");?>?s=250&q=<?=urlencode("/package/guestpass_install?token={$token}")?>">
        </p>

    </div>
</div>

<div class="visible-xs">
    <?=block('pkg_infopanel')?>
</div>
